[2023-02-24T04:00:38.839+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: ingest_bo_voucher_report.ingest_bo_voucher_report scheduled__2023-02-22T19:00:00+00:00 [queued]>
[2023-02-24T04:00:38.855+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: ingest_bo_voucher_report.ingest_bo_voucher_report scheduled__2023-02-22T19:00:00+00:00 [queued]>
[2023-02-24T04:00:38.857+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2023-02-24T04:00:38.858+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 6 of 9
[2023-02-24T04:00:38.860+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2023-02-24T04:00:38.883+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): ingest_bo_voucher_report> on 2023-02-22 19:00:00+00:00
[2023-02-24T04:00:38.890+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 506 to run task
[2023-02-24T04:00:38.896+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'ingest_bo_voucher_report', 'ingest_bo_voucher_report', 'scheduled__2023-02-22T19:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/ingest_bo_voucher_report.py', '--cfg-path', '/tmp/tmpmvf39136']
[2023-02-24T04:00:38.900+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 7: Subtask ingest_bo_voucher_report
[2023-02-24T04:00:38.985+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: ingest_bo_voucher_report.ingest_bo_voucher_report scheduled__2023-02-22T19:00:00+00:00 [running]> on host 8d8c6b853c06
[2023-02-24T04:00:39.069+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=ingest_bo_voucher_report
AIRFLOW_CTX_TASK_ID=ingest_bo_voucher_report
AIRFLOW_CTX_EXECUTION_DATE=2023-02-22T19:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-22T19:00:00+00:00
[2023-02-24T04:00:44.913+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Error: relation "raw_data.partnership_cinema_daily" does not exist
LINE 1: INSERT INTO raw_data.partnership_cinema_daily(date_key,date_...
                    ^
[2023-02-24T04:00:44.918+0000] {python.py:177} INFO - ðŸ¤ª Done. Returned value was: None
[2023-02-24T04:00:44.923+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as SUCCESS. dag_id=ingest_bo_voucher_report, task_id=ingest_bo_voucher_report, execution_date=20230222T190000, start_date=20230224T040038, end_date=20230224T040044
[2023-02-24T04:00:44.953+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 0
[2023-02-24T04:00:44.972+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
