[2022-12-05T07:44:52.550+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-12-05T07:24:23.686370+00:00 [queued]>
[2022-12-05T07:44:52.561+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-12-05T07:24:23.686370+00:00 [queued]>
[2022-12-05T07:44:52.562+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-05T07:44:52.563+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 5 of 8
[2022-12-05T07:44:52.564+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-05T07:44:52.582+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_postgres_sources> on 2022-12-05 07:24:23.686370+00:00
[2022-12-05T07:44:52.588+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 829 to run task
[2022-12-05T07:44:52.592+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_postgres_sources', 'manual__2022-12-05T07:24:23.686370+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/ingest_dwh_daily.py', '--cfg-path', '/tmp/tmpjec2oag5']
[2022-12-05T07:44:52.594+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 17: Subtask get_raw_data_from_postgres_sources
[2022-12-05T07:44:52.645+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-12-05T07:24:23.686370+00:00 [running]> on host 2387a8df1781
[2022-12-05T07:44:52.698+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_postgres_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-12-05T07:24:23.686370+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-05T07:24:23.686370+00:00
[2022-12-05T07:44:52.709+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Start getting data from source - Table: users
[2022-12-05T07:44:52.715+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Found 100 records need to be inserted
[2022-12-05T07:44:52.731+0000] {logging_mixin.py:137} INFO - ðŸ¤ª     user_id        name                           email        mobile  location
0         1      Rivera          j.rivera24@hotmail.com  360-245-6987  ThaiLand
1         2    Phillips         isaacjoseph@outlook.com  629-424-2453  ThaiLand
2         3        Ross           m.ross@rocketmail.com  702-025-6721  ThaiLand
3         4       Lewis                 hjlewis@aol.com  220-616-2376  ThaiLand
4         5      Walker      amandamariewalker@live.com  216-598-6288  ThaiLand
..      ...         ...                             ...           ...       ...
95       96    Phillips          m_phillips@outlook.com  231-134-2462  ThaiLand
96       97       Green      danielle.green14@ymail.com  931-400-6351  ThaiLand
97       98  Washington          b.washington@gmail.com  330-697-0313  ThaiLand
98       99  Washington     amwashington@rocketmail.com  267-828-6522  ThaiLand
99      100      Cooper  charles_t_cooper80@outlook.com  815-136-3329  ThaiLand

[100 rows x 5 columns]
[2022-12-05T07:44:52.732+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Start ingesting data from source to DW - Table: users
[2022-12-05T07:44:52.733+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/processing/ingest_psql_source.py", line 28, in ingest_psql_source
    postgres_handler.action_db('insert', df, table)
  File "/airflow/dags/db_handler/postgres_handler.py", line 87, in action_db
    if action == 'select':
  File "/opt/bitnami/python/lib/python3.8/site-packages/pandas/core/generic.py", line 1527, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
[2022-12-05T07:44:52.743+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as UP_FOR_RETRY. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_postgres_sources, execution_date=20221205T072423, start_date=20221205T074452, end_date=20221205T074452
[2022-12-05T07:44:52.755+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 17 for task get_raw_data_from_postgres_sources (The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().; 829)
[2022-12-05T07:44:52.766+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2022-12-05T07:44:52.780+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
