[2022-12-05T07:43:35.881+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-12-05T07:24:23.686370+00:00 [queued]>
[2022-12-05T07:43:35.918+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-12-05T07:24:23.686370+00:00 [queued]>
[2022-12-05T07:43:35.920+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-05T07:43:35.921+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 3 of 4
[2022-12-05T07:43:35.923+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-05T07:43:35.950+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_postgres_sources> on 2022-12-05 07:24:23.686370+00:00
[2022-12-05T07:43:35.955+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 805 to run task
[2022-12-05T07:43:35.962+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_postgres_sources', 'manual__2022-12-05T07:24:23.686370+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/ingest_dwh_daily.py', '--cfg-path', '/tmp/tmpfkkqazx4']
[2022-12-05T07:43:35.967+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 14: Subtask get_raw_data_from_postgres_sources
[2022-12-05T07:43:36.049+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources manual__2022-12-05T07:24:23.686370+00:00 [running]> on host 2387a8df1781
[2022-12-05T07:43:36.105+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_postgres_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-12-05T07:24:23.686370+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-05T07:24:23.686370+00:00
[2022-12-05T07:43:36.117+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Start getting data from source - Table: users
[2022-12-05T07:43:36.125+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Found 100 records need to be inserted
[2022-12-05T07:43:36.126+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Start ingesting data from source to DW - Table: users
[2022-12-05T07:43:36.128+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/processing/ingest_psql_source.py", line 27, in ingest_psql_source
    postgres_handler.action_db('insert', df, table)
  File "/airflow/dags/db_handler/postgres_handler.py", line 87, in action_db
    if action == 'select':
  File "/opt/bitnami/python/lib/python3.8/site-packages/pandas/core/generic.py", line 1527, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
[2022-12-05T07:43:36.148+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as UP_FOR_RETRY. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_postgres_sources, execution_date=20221205T072423, start_date=20221205T074335, end_date=20221205T074336
[2022-12-05T07:43:36.234+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 14 for task get_raw_data_from_postgres_sources (The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().; 805)
[2022-12-05T07:43:36.261+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2022-12-05T07:43:36.315+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
