[2022-12-09T18:11:35.011+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources scheduled__2022-12-07T19:00:00+00:00 [queued]>
[2022-12-09T18:11:35.019+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources scheduled__2022-12-07T19:00:00+00:00 [queued]>
[2022-12-09T18:11:35.020+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-09T18:11:35.022+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 6 of 9
[2022-12-09T18:11:35.023+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-09T18:11:35.039+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_postgres_sources> on 2022-12-07 19:00:00+00:00
[2022-12-09T18:11:35.042+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 217 to run task
[2022-12-09T18:11:35.047+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_postgres_sources', 'scheduled__2022-12-07T19:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/ingest_dwh_daily.py', '--cfg-path', '/tmp/tmp96x8iv9s']
[2022-12-09T18:11:35.049+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 12: Subtask get_raw_data_from_postgres_sources
[2022-12-09T18:11:35.111+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources scheduled__2022-12-07T19:00:00+00:00 [running]> on host 31f0fd0ea32a
[2022-12-09T18:11:35.166+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_postgres_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T19:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-07T19:00:00+00:00
[2022-12-09T18:11:35.175+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Start getting data from source Postgres - Table: users
[2022-12-09T18:11:35.189+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Found 100 records need to be inserted
[2022-12-09T18:11:35.190+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Start ingesting data from source Postgres to DW - Table: users
[2022-12-09T18:11:35.192+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/processing/ingest_psql_source.py", line 69, in ingest_psql_source
    insert_data_to_dwh(postgres_handler=postgres_handler, data=data, table=table['table'])
  File "/airflow/dags/processing/ingest_psql_source.py", line 18, in insert_data_to_dwh
    postgres_handler.action_db(data=data, table=table, action='insert')
  File "/airflow/dags/db_handler/master_handler.py", line 74, in action_db
    return self._push_data(data, table)
  File "/airflow/dags/db_handler/master_handler.py", line 40, in _push_data
    print('hello world', self.dwh_connection)
AttributeError: 'PostgresHandler' object has no attribute 'dwh_connection'
[2022-12-09T18:11:35.202+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as UP_FOR_RETRY. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_postgres_sources, execution_date=20221207T190000, start_date=20221209T181135, end_date=20221209T181135
[2022-12-09T18:11:35.215+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 12 for task get_raw_data_from_postgres_sources ('PostgresHandler' object has no attribute 'dwh_connection'; 217)
[2022-12-09T18:11:35.260+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2022-12-09T18:11:35.279+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
