[2022-12-09T07:33:24.791+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources scheduled__2022-12-07T19:00:00+00:00 [queued]>
[2022-12-09T07:33:24.800+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources scheduled__2022-12-07T19:00:00+00:00 [queued]>
[2022-12-09T07:33:24.801+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-09T07:33:24.802+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 1 of 4
[2022-12-09T07:33:24.802+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-09T07:33:24.816+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_postgres_sources> on 2022-12-07 19:00:00+00:00
[2022-12-09T07:33:24.819+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 64 to run task
[2022-12-09T07:33:24.824+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_postgres_sources', 'scheduled__2022-12-07T19:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ingest_dwh_daily.py', '--cfg-path', '/tmp/tmp7b5peroc']
[2022-12-09T07:33:24.826+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 3: Subtask get_raw_data_from_postgres_sources
[2022-12-09T07:33:24.881+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources scheduled__2022-12-07T19:00:00+00:00 [running]> on host 83309ba15041
[2022-12-09T07:33:24.933+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_postgres_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T19:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-07T19:00:00+00:00
[2022-12-09T07:33:24.941+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Start getting data from source Postgres - Table: users
[2022-12-09T07:33:24.948+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Found 100 records need to be inserted
[2022-12-09T07:33:24.949+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Start ingesting data from source Postgres to DW - Table: users
[2022-12-09T07:33:24.949+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/processing/ingest_psql_source.py", line 69, in ingest_psql_source
    insert_data_to_dwh(data, table['table'])
TypeError: insert_data_to_dwh() missing 1 required positional argument: 'table'
[2022-12-09T07:33:24.958+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as UP_FOR_RETRY. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_postgres_sources, execution_date=20221207T190000, start_date=20221209T073324, end_date=20221209T073324
[2022-12-09T07:33:24.970+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 3 for task get_raw_data_from_postgres_sources (insert_data_to_dwh() missing 1 required positional argument: 'table'; 64)
[2022-12-09T07:33:24.997+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2022-12-09T07:33:25.013+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
[2022-12-09T17:54:49.080+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources scheduled__2022-12-07T19:00:00+00:00 [queued]>
[2022-12-09T17:54:49.089+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources scheduled__2022-12-07T19:00:00+00:00 [queued]>
[2022-12-09T17:54:49.090+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-09T17:54:49.090+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 1 of 4
[2022-12-09T17:54:49.091+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-09T17:54:49.103+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_postgres_sources> on 2022-12-07 19:00:00+00:00
[2022-12-09T17:54:49.106+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 64 to run task
[2022-12-09T17:54:49.110+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_postgres_sources', 'scheduled__2022-12-07T19:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/ingest_dwh_daily.py', '--cfg-path', '/tmp/tmprk7w33ez']
[2022-12-09T17:54:49.112+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 3: Subtask get_raw_data_from_postgres_sources
[2022-12-09T17:54:49.162+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_postgres_sources scheduled__2022-12-07T19:00:00+00:00 [running]> on host 31f0fd0ea32a
[2022-12-09T17:54:49.213+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_postgres_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T19:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-07T19:00:00+00:00
[2022-12-09T17:54:49.220+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Start getting data from source Postgres - Table: users
[2022-12-09T17:54:49.227+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Found 100 records need to be inserted
[2022-12-09T17:54:49.228+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Start ingesting data from source Postgres to DW - Table: users
[2022-12-09T17:54:49.230+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/processing/ingest_psql_source.py", line 69, in ingest_psql_source
    insert_data_to_dwh(postgres_handler=postgres_handler, data=data, table=table['table'])
  File "/airflow/dags/processing/ingest_psql_source.py", line 18, in insert_data_to_dwh
    postgres_handler.action_db(data=data, table=table, action='insert')
  File "/airflow/dags/db_handler/master_handler.py", line 73, in action_db
    return self._push_data(data, table)
  File "/airflow/dags/db_handler/master_handler.py", line 45, in _push_data
    cursor = self.dwh_connection.cursor()
AttributeError: 'PostgresHandler' object has no attribute 'dwh_connection'
[2022-12-09T17:54:49.238+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as UP_FOR_RETRY. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_postgres_sources, execution_date=20221207T190000, start_date=20221209T175449, end_date=20221209T175449
[2022-12-09T17:54:49.249+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 3 for task get_raw_data_from_postgres_sources ('PostgresHandler' object has no attribute 'dwh_connection'; 64)
[2022-12-09T17:54:49.284+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2022-12-09T17:54:49.300+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
