[2022-12-07T16:34:44.216+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources manual__2022-12-07T16:07:12.235594+00:00 [queued]>
[2022-12-07T16:34:44.224+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources manual__2022-12-07T16:07:12.235594+00:00 [queued]>
[2022-12-07T16:34:44.225+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-07T16:34:44.226+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 1 of 4
[2022-12-07T16:34:44.226+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-12-07T16:34:44.240+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_mysql_sources> on 2022-12-07 16:07:12.235594+00:00
[2022-12-07T16:34:44.244+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 360 to run task
[2022-12-07T16:34:44.248+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_mysql_sources', 'manual__2022-12-07T16:07:12.235594+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/ingest_dwh_daily.py', '--cfg-path', '/tmp/tmphxbbji_5']
[2022-12-07T16:34:44.250+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 23: Subtask get_raw_data_from_mysql_sources
[2022-12-07T16:34:44.294+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources manual__2022-12-07T16:07:12.235594+00:00 [running]> on host db3df0a6f633
[2022-12-07T16:34:44.342+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_mysql_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T16:07:12.235594+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-07T16:07:12.235594+00:00
[2022-12-07T16:34:44.350+0000] {taskinstance.py:1851} ERROR - ðŸ¤ª Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/python/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/airflow/dags/processing/ingest_mysql_source.py", line 16, in ingest_mysql_source
    for index, table in enumerate(MysqlStatements.list_tables):
AttributeError: type object 'MysqlStatements' has no attribute 'list_tables'
[2022-12-07T16:34:44.356+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as UP_FOR_RETRY. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_mysql_sources, execution_date=20221207T160712, start_date=20221207T163444, end_date=20221207T163444
[2022-12-07T16:34:44.366+0000] {standard_task_runner.py:100} ERROR - ðŸ¤ª Failed to execute job 23 for task get_raw_data_from_mysql_sources (type object 'MysqlStatements' has no attribute 'list_tables'; 360)
[2022-12-07T16:34:44.381+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 1
[2022-12-07T16:34:44.393+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
