[2022-11-30T07:30:23.124+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources manual__2022-11-30T05:03:14.223869+00:00 [queued]>
[2022-11-30T07:30:23.134+0000] {taskinstance.py:1165} INFO - ðŸ¤ª Dependencies all met for <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources manual__2022-11-30T05:03:14.223869+00:00 [queued]>
[2022-11-30T07:30:23.134+0000] {taskinstance.py:1362} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-11-30T07:30:23.135+0000] {taskinstance.py:1363} INFO - ðŸ¤ª Starting attempt 6 of 9
[2022-11-30T07:30:23.136+0000] {taskinstance.py:1364} INFO - ðŸ¤ª 
--------------------------------------------------------------------------------
[2022-11-30T07:30:23.150+0000] {taskinstance.py:1383} INFO - ðŸ¤ª Executing <Task(PythonOperator): get_raw_data_from_mysql_sources> on 2022-11-30 05:03:14.223869+00:00
[2022-11-30T07:30:23.153+0000] {standard_task_runner.py:55} INFO - ðŸ¤ª Started process 836 to run task
[2022-11-30T07:30:23.158+0000] {standard_task_runner.py:82} INFO - ðŸ¤ª Running: ['airflow', 'tasks', 'run', 'get_raw_data_from_sources', 'get_raw_data_from_mysql_sources', 'manual__2022-11-30T05:03:14.223869+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/get_data_from_sources.py', '--cfg-path', '/tmp/tmp3sq4onfu']
[2022-11-30T07:30:23.160+0000] {standard_task_runner.py:83} INFO - ðŸ¤ª Job 61: Subtask get_raw_data_from_mysql_sources
[2022-11-30T07:30:23.212+0000] {task_command.py:376} INFO - ðŸ¤ª Running <TaskInstance: get_raw_data_from_sources.get_raw_data_from_mysql_sources manual__2022-11-30T05:03:14.223869+00:00 [running]> on host 298e6b8d1257
[2022-11-30T07:30:23.295+0000] {taskinstance.py:1590} INFO - ðŸ¤ª Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=gp.data@galaxy.com.vn
AIRFLOW_CTX_DAG_OWNER=data_team
AIRFLOW_CTX_DAG_ID=get_raw_data_from_sources
AIRFLOW_CTX_TASK_ID=get_raw_data_from_mysql_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-11-30T05:03:14.223869+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-30T05:03:14.223869+00:00
[2022-11-30T07:30:23.359+0000] {logging_mixin.py:137} INFO - ðŸ¤ª Error: duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(1) already exists.
[2022-11-30T07:30:23.361+0000] {python.py:177} INFO - ðŸ¤ª Done. Returned value was: None
[2022-11-30T07:30:23.369+0000] {taskinstance.py:1401} INFO - ðŸ¤ª Marking task as SUCCESS. dag_id=get_raw_data_from_sources, task_id=get_raw_data_from_mysql_sources, execution_date=20221130T050314, start_date=20221130T073023, end_date=20221130T073023
[2022-11-30T07:30:23.412+0000] {local_task_job.py:159} INFO - ðŸ¤ª Task exited with return code 0
[2022-11-30T07:30:23.429+0000] {taskinstance.py:2623} INFO - ðŸ¤ª 0 downstream tasks scheduled from follow-on schedule check
